adknow_project/adknow/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('about-us/', views.about_us, name='about-us'),
    path('conversation/', views.conversation, name='conversation'),
]

adknow_project/adknow_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('adknow.urls')),
    path('registration/', include('user_auth.urls')),
    path('admin/', admin.site.urls),
]

adknow_project/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
]

adknow_project/adknow/models.py
from django.db import models

# Create your models here.

adknow_project/user_auth/models.py
from django.db import models

# Create your models here.

adknow_project/user_auth/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

adknow_project/adknow/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'adknow/index.html')


def conversation(request):
    return render(request, 'adknow/conversation.html')


def about_us(request):
    return render(request, 'adknow/about_us.html')

adknow_project/user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout 
from .forms import SignupForm, LoginForm

def index(request):
    return render(request, 'user_auth/index.html')

# signup page
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('registration:login')
    else:
        form = SignupForm()
    return render(request, 'user_auth/signup.html', {'form': form})

# login page
def user_login(request):
    account_exist = True
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)    
                return redirect('home:index')
            else:
                account_exist = False
    else:
        form = LoginForm()
    return render(
        request, 
        'user_auth/login.html', 
        {
            'form': form, 
            'account_exist': account_exist,
        }
    )

# logout page
def user_logout(request):
    logout(request)
    return redirect('home:index')

adknow_project/adknow/templates/adknow/about_us.html
{% load static %}
<link rel="stylesheet" href="{% static 'adknow/about_us.css' %}">

<body class="about-screen">
    <div class="back-button">
        <a href="{% url 'home:index' %}">
            <img src="{% static 'icons/left.png' %}" alt="Back to homepage">
        </a>
    </div>
    <div class="body">
        <h1 class="title">About Us</h1>
        <p class="description">
            ADKnow is your go-to chatbot for everything about Ateneo De Naga University. 
            It’s like your personal guide, answering your questions about our campus, facilities, 
            and traditions. And the cool part? You can get all this info without even being on campus. 
            So, whether you’re a student, planning to join us, or just curious, ADKnow is here to help. 
            Welcome to the Ateneo journey!
        </p>
    </div>
</body>

adknow_project/adknow/templates/adknow/conversation.html
{% load static %}
<link rel="stylesheet" href="{% static 'adknow/conversation.css' %}">

<body>
    <div id="chat" class="container"></div>
    <div class="chatbox">
        <div class="ssbtn-container">
            <img id="ssbtn" src="{% static 'icons/screenshot_button.png' %}" alt="Screenshot button">
        </div>
        <input id="input" type="text" onkeydown="if(event.key === 'Enter') addMessage()" placeholder="Type a message...">
        <div class="sendbtn-container">
            <button id="send-btn" onclick="addMessage()"><img src="{% static 'icons/send_button.png' %}" alt="Send button"></button>
        </div>
    </div>
    <script>
        function addMessage() {
            var input = document.getElementById('input');
            var chat = document.getElementById('chat');
            var userDiv = document.createElement('div');
            var userLabel = document.createElement('div');
            userLabel.textContent = 'User';
            userLabel.className = 'message user-label';
            userDiv.textContent = input.value;
            userDiv.className = 'message user';
            chat.appendChild(userLabel);
            chat.appendChild(userDiv);
            var programDiv = document.createElement('div');
            var programLabel = document.createElement('div');
            programLabel.textContent = 'AdKnow';
            programLabel.className = 'message program-label';
            programDiv.textContent = 'Hello there, Lorem ipsum';
            programDiv.className = 'message program';
            chat.appendChild(programLabel);
            chat.appendChild(programDiv);
            input.value = '';
        }
    </script>
</body>

adknow_project/adknow/templates/adknow/index.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AdKnow Chatbot</title>
    <link rel="stylesheet" href="{% static 'adknow/index.css' %}">
</head>
<body class="main-screen">
    <div class="header">
        <div class="header__user-greeting">
            {% if request.user.is_authenticated %}
                <p>Hello there, {{ request.user.username }}</p>
            {% endif %}
        </div>
        <div class="header__navigation-links">
            <p><a href="{% url 'home:about-us' %}">About Us</a></p>
            {% if request.user.is_authenticated %}
                <p><a href="{% url 'registration:logout' %}">Logout</a></p>
            {% else %}
                <p><a href="{% url 'registration:signup' %}">Signup</a></p>
            {% endif %}
        </div>
    </div>
    <div class="body">
        <div class="title">
            <img src="{% static 'icons/adknow_logo.png' %}" alt="AdKnow logo">
            <h1>AdKnow</h1>
        </div>
        <main>
            <div id="chat-interface">
              <form id="chat-form" class="input-container">
                <input type="text" id="chat-input" placeholder="Type message...">
                <button id="send-btn" onclick="redirectToSecondPage()"><img src="{% static 'icons/send_button.png' %}" alt="Send button"></button>
              </form>
            </div>
            <nav>
              <ul>
                <li><a href="#campus" class="nav-tab">Campus</a></li>
                <li><a href="#offices" class="nav-tab">Offices</a></li>
                <li><a href="#academics" class="nav-tab">Academics</a></li>
                <li><a href="#history" class="nav-tab">History</a></li>
              </ul>
            </nav>
            <div id="content">
              <!-- Content for each tab goes here -->
            </div>
            <div class="tabs-container">
                <div class="tab-box">
                    <button class="cont-tab" onclick="redirectToSecondPage()">Option 1<p>Option 1 Description</p></button>
                </div>
                <div class="tab-box">
                    <button class="cont-tab" onclick="redirectToSecondPage()">Option 2<p>Option 2 Description</p></button>
                </div>
                <div class="tab-box">
                    <button class="cont-tab" onclick="redirectToSecondPage()">Option 3<p>Option 3 Description</p></button>
                </div>
                <div class="tab-box">
                    <button class="cont-tab" onclick="redirectToSecondPage()">Option 4<p>Option 4 Description</p></button>
                </div>
            </div>
        </main>
        <script src="{% static 'adknow/index.js' %}" async></script>
    </div>
</body>

adknow_project/user_auth/templates/user_auth/conversation.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'user_auth/conversation.css' %}">
    
</head>
<body>
    <div id="chat" class="container"></div>
    <input id="input" type="text" onkeydown="if(event.key === 'Enter') addMessage()" placeholder="Type a message...">
    <script>
        function addMessage() {
            var input = document.getElementById('input');
            var chat = document.getElementById('chat');
            var userDiv = document.createElement('div');
            userDiv.textContent = input.value;
            userDiv.className = 'message user';
            chat.appendChild(userDiv);
            var programDiv = document.createElement('div');
            programDiv.textContent = 'Hello there, Lorem ipsum';
            programDiv.className = 'message program';
            chat.appendChild(programDiv);
            input.value = '';
        }
    </script>
</body>
</html>

adknow_project/user_auth/templates/user_auth/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="{% static 'user_auth/index.css' %}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AdKnow Chatbot</title>
</head>

<body class="main-screen">
  <div class="header">
    <div class="header__user-greeting">
        {% if request.user.is_authenticated %}
            <p>Hello there, {{ request.user.username }}</p>
        {% endif %}
    </div>
    <div class="header__navigation-links">
        <p><a href="{% url 'home:about-us' %}">About Us</a></p>
        {% if request.user.is_authenticated %}
            <p><a href="{% url 'registration:logout' %}">Logout</a></p>
        {% else %}
            <p><a href="{% url 'registration:signup' %}">Signup</a></p>
        {% endif %}
    </div>
  </div>
  <div class="body">
    <h1 class="title">AdKnow</h1>
    <div id="chat-interface">
      <form id="chat-form" class="input-container">
          <input type="text" id="chat-input" placeholder="Type message...">
          <button id="send-btn" onclick="redirectToSecondPage()">Send</button>
      </form>
    </div>
    <nav>
        <ul>
            <li><a href="#campus" class="tab">Campus</a></li>
            <li><a href="#offices" class="tab">Offices</a></li>
            <li><a href="#academics" class="tab">Academics</a></li>
            <li><a href="#history" class="tab">History</a></li>
        </ul>
    </nav>
    <div id="content">
        <!-- Content for each tab goes here -->
    </div>
    <div class="tabs-container">
        <div class="tab-box">
            <button class="tab" onclick="showContent('option1')">Option 1</button>
        </div>
        <div class="tab-box">
            <button class="tab" onclick="showContent('option2')">Option 2</button>
        </div>
        <div class="tab-box">
            <button class="tab" onclick="showContent('option3')">Option 3</button>
        </div>
        <div class="tab-box">
            <button class="tab" onclick="showContent('option4')">Option 4</button>
        </div>
    </div>
  </div>
        
  <script src="{% static 'user_auth/index.js' %}" async></script>
</body>
</html>



adknow_project/user_auth/templates/user_auth/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'user_auth/login.css' %}">

<body class="screen">
    <div class="container">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
            {% if account_exist == False %}
                <div class="error_msg">
                    <p>Username or password does not exist</p>
                </div>
            {% endif %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="{{ form.username.name }}" class="form-control" required>
            </div>
            <br>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="{{ form.password.name }}" class="form-control" required>
            </div>
            <br>
            <div class="login_button">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
            <br>
            <div class="dont_have_account">
                <a href="{% url 'registration:signup' %}" class="btn btn-link">Don't have an account? Create one</a>
            </div>
        </form>
    </div>
    
</body>



adknow_project/user_auth/templates/user_auth/signup.html
{% load static %}
<link rel="stylesheet" href="{% static 'user_auth/signup.css' %}">

<body class="screen">
    <div class="container">
        <h1>Signup</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="user_input_tab">
                <p>{{ form.username.label_tag }} <br> {{ form.username }}</p>
                {% if form.username.errors %}
                    <p>{{ form.username.errors }}</p>
                {% endif %}
            </div>
            <br>
            <div class="user_input_tab">
                <p>{{ form.password1.label_tag }} <br> {{ form.password1 }}</p>
                {% if form.password1.errors %}
                    <p>{{ form.password1.errors }}</p>
                {% endif %}
            </div>
            <br>
            <div class="user_input_tab">
                <p>{{ form.password2.label_tag }} <br> {{ form.password2 }}</p>
                {% if form.password2.errors %}
                    <p>{{ form.password2.errors }}</p>
                {% endif %}
            </div>
            <br>
            <div class="signup_button">
                <button type="submit">Signup</button>
            </div>
            <br>
            <div class="already_have_account">
                <a href="{% url 'registration:login' %}">Already have account?</a>
            </div>
        </form>
    </div>
</body>

